document.write("<table width='778' border='0' align='center' cellpadding='0' cellspacing='0'>");
document.write("<tr>");
document.write("    <td width='150'><table width='80%'  border='0' cellspacing='0' cellpadding='0'>");
document.write("      <tr align='center'>");
document.write("        <td><img src='http://img.job365.net/biaoshi_jindun.gif' width='40' height='48'></td>");
document.write("        <td><a href='http://www.job365.net/General/icp/wangan.htm' target='_blank'><img src='http://img.job365.net/biaoshi_wangan.gif' width='34' height='45' border='0'></a></td>");
document.write("      </tr>");
document.write("      <tr align='center'>");
document.write("        <td colspan='2'>粤ICP证030359 </td>");
document.write("        </tr>");
document.write("    </table></td>");
document.write("    <td valign='top'><table width='100%'  border='0' cellpadding='0' cellspacing='0' bgcolor='#285ABA'>");
document.write("      <tr>");
document.write("        <td align='center' style='color:#FFFFFF'><a  href='http://www.job365.net/General/About.htm' class='menu'>关于我们</a> | <a  href='http://www.job365.net/General/contactus.htm' class='menu'>联系我们</a> | <a  href='http://www.job365.net/General/navigate.htm' class='menu'>网站地图</a> | <a  href='http://www.job365.net/General/PostWork.htm' class='menu'>投稿指南</a> | <a  href='http://www.job365.net/General/friendlink.htm' class='menu'>友情链接</a> </td>");
document.write("        <td width='70' align='right'><img src='http://img.job365.net/jobseeker_bottom.gif' width='14' height='27'></td>");
//| <a  href='http://www.job365.net/General/adv.htm' class='menu'>广告报价</a> | <a  href='http://www.job365.net/General/vip.htm' class='menu'>会员服务</a>
document.write("      </tr>");
document.write("    </table>");
document.write("      <table width='100%'  border='0' cellspacing='0' cellpadding='0'>");
document.write("        <tr>");
document.write("          <td><hr size='1' color='#E3EDFF'>");
document.write("        </td></tr>");
document.write("        <tr>");
document.write("          <td>版权所有 深圳西部人力资源市场 &copy; 2000-2006&nbsp;&nbsp; ");
//document.write(" 客户服务：<atarget=blank href='http://wpa.qq.com/msgrd?V=1&Uin=498832587&Site=天天工作网&Menu=yes'><img border='0' SRC='http://wpa.qq.com/pa?p=1:498832587:1' alt='点击这里给我们发消息' align='absmiddle'></a>");
document.write("		  <script src='http://www.job365.net/count/count.asp?style=0'></script>	")
document.write("          <IMG width=0 height=0 src='http://www.jobems.com/Bin/GetStatus.asp' border='0'></td></tr>");
document.write("      </table>");
document.write("  </td></tr>");
document.write("</table>");
