<SELECT id=nation name=nation style="width:120px;">
                            <OPTION value=汉族 <% If Nation = "汉族" Then Response.write "Selected" %>>汉族</OPTION>
                            <OPTION value=蒙古族 <% If Nation = "蒙古族" Then Response.write "Selected" %>>蒙古族</OPTION>
                            <OPTION value=满族 <% If Nation = "满族" Then Response.write "Selected" %>>满族</OPTION>
                            <OPTION value=回族 <% If Nation = "回族" Then Response.write "Selected" %>>回族</OPTION>
                            <OPTION value=藏族 <% If Nation = "藏族" Then Response.write "Selected" %>>藏族</OPTION>
                            <OPTION value=维吾尔族 <% If Nation = "维吾尔族" Then Response.write "Selected" %>>维吾尔族</OPTION>
                            <OPTION value=壮族 <% If Nation = "壮族" Then Response.write "Selected" %>>壮族</OPTION>
                            <OPTION value=苗族 <% If Nation = "苗族" Then Response.write "Selected" %>>苗族</OPTION>
                            <OPTION value=彝族 <% If Nation = "彝族" Then Response.write "Selected" %>>彝族</OPTION>
                            <OPTION value=朝鲜族 <% If Nation = "朝鲜族" Then Response.write "Selected" %>>朝鲜族</OPTION>
                            <OPTION value=布依族 <% If Nation = "布依族" Then Response.write "Selected" %>>布依族</OPTION>
                            <OPTION value=侗族 <% If Nation = "侗族" Then Response.write "Selected" %>>侗族</OPTION>
                            <OPTION value=瑶族 <% If Nation = "瑶族" Then Response.write "Selected" %>>瑶族</OPTION>
                            <OPTION value=白族 <% If Nation = "白族" Then Response.write "Selected" %>>白族</OPTION>
                            <OPTION value=土家族 <% If Nation = "土家族" Then Response.write "Selected" %>>土家族</OPTION>
                            <OPTION value=哈尼族 <% If Nation = "哈尼族" Then Response.write "Selected" %>>哈尼族</OPTION>
                            <OPTION value=哈萨克族 <% If Nation = "哈萨克族" Then Response.write "Selected" %>>哈萨克族</OPTION>
                            <OPTION value=傣族 <% If Nation = "傣族" Then Response.write "Selected" %>>傣族</OPTION>
                            <OPTION value=黎族 <% If Nation = "黎族" Then Response.write "Selected" %>>黎族</OPTION>
                            <OPTION value=傈僳族 <% If Nation = "傈僳族" Then Response.write "Selected" %>>傈僳族</OPTION>
                            <OPTION value=佤族 <% If Nation = "佤族" Then Response.write "Selected" %>>佤族</OPTION>
                            <OPTION value=畲族 <% If Nation = "畲族" Then Response.write "Selected" %>>畲族</OPTION>
                            <OPTION value=高山族 <% If Nation = "高山族" Then Response.write "Selected" %>>高山族</OPTION>
                            <OPTION value=拉祜族 <% If Nation = "拉祜族" Then Response.write "Selected" %>>拉祜族</OPTION>
                            <OPTION value=水族 <% If Nation = "水族" Then Response.write "Selected" %>>水族</OPTION>
                            <OPTION value=东乡族 <% If Nation = "东乡族" Then Response.write "Selected" %>>东乡族</OPTION>
                            <OPTION value=纳西族 <% If Nation = "纳西族" Then Response.write "Selected" %>>纳西族</OPTION>
                            <OPTION value=景颇族 <% If Nation = "景颇族" Then Response.write "Selected" %>>景颇族</OPTION>
                            <OPTION value=柯尔克孜族 <% If Nation = "柯尔克孜族" Then Response.write "Selected" %>>柯尔克孜族</OPTION>
                            <OPTION value=土族 <% If Nation = "土族" Then Response.write "Selected" %>>土族</OPTION>
                            <OPTION value=达斡尔族 <% If Nation = "达斡尔族" Then Response.write "Selected" %>>达斡尔族</OPTION>
                            <OPTION value=仫佬族 <% If Nation = "仫佬族" Then Response.write "Selected" %>>仫佬族</OPTION>
                            <OPTION value=羌族 <% If Nation = "羌族" Then Response.write "Selected" %>>羌族</OPTION>
                            <OPTION value=布朗族 <% If Nation = "布朗族" Then Response.write "Selected" %>>布朗族</OPTION>
                            <OPTION value=撒拉族 <% If Nation = "撒拉族" Then Response.write "Selected" %>>撒拉族</OPTION>
                            <OPTION value=毛南族 <% If Nation = "毛南族" Then Response.write "Selected" %>>毛南族</OPTION>
                            <OPTION value=仡佬族 <% If Nation = "仡佬族" Then Response.write "Selected" %>>仡佬族</OPTION>
                            <OPTION value=锡伯族 <% If Nation = "锡伯族" Then Response.write "Selected" %>>锡伯族</OPTION>
                            <OPTION value=阿昌族 <% If Nation = "阿昌族" Then Response.write "Selected" %>>阿昌族</OPTION>
                            <OPTION value=普米族 <% If Nation = "普米族" Then Response.write "Selected" %>>普米族</OPTION>
                            <OPTION value=塔吉克族 <% If Nation = "塔吉克族" Then Response.write "Selected" %>>塔吉克族</OPTION>
                            <OPTION value=怒族 <% If Nation = "怒族" Then Response.write "Selected" %>>怒族</OPTION>
                            <OPTION value=乌兹别克族 <% If Nation = "乌兹别克族" Then Response.write "Selected" %>>乌兹别克族</OPTION>
                            <OPTION value=俄罗斯族 <% If Nation = "俄罗斯族" Then Response.write "Selected" %>>俄罗斯族</OPTION>
                            <OPTION value=鄂温克族 <% If Nation = "鄂温克族" Then Response.write "Selected" %>>鄂温克族</OPTION>
                            <OPTION value=德昂族 <% If Nation = "德昂族" Then Response.write "Selected" %>>德昂族</OPTION>
                            <OPTION value=保安族 <% If Nation = "保安族" Then Response.write "Selected" %>>保安族</OPTION>
                            <OPTION value=裕固族 <% If Nation = "裕固族" Then Response.write "Selected" %>>裕固族</OPTION>
                            <OPTION value=京族 <% If Nation = "京族" Then Response.write "Selected" %>>京族</OPTION>
                            <OPTION value=塔塔尔族 <% If Nation = "塔塔尔族" Then Response.write "Selected" %>>塔塔尔族</OPTION>
                            <OPTION value=独龙族 <% If Nation = "独龙族" Then Response.write "Selected" %>>独龙族</OPTION>
                            <OPTION value=鄂伦春族 <% If Nation = "鄂伦春族" Then Response.write "Selected" %>>鄂伦春族</OPTION>
                            <OPTION value=赫哲族 <% If Nation = "赫哲族" Then Response.write "Selected" %>>赫哲族</OPTION>
                            <OPTION value=门巴族 <% If Nation = "门巴族" Then Response.write "Selected" %>>门巴族</OPTION>
                            <OPTION value=珞巴族 <% If Nation = "珞巴族" Then Response.write "Selected" %>>珞巴族</OPTION>
                            <OPTION value=基诺族 <% If Nation = "基诺族" Then Response.write "Selected" %>>基诺族</OPTION>
                            <OPTION value=其它 <% If Nation = "其它" Then Response.write "Selected" %>>其它</OPTION>
                          </SELECT>